# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-02-04 07:49
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('cmtUid', models.IntegerField(primary_key=True, serialize=False)),
                ('cmtEditedYN', models.CharField(max_length=1)),
            ],
        ),
        migrations.CreateModel(
            name='CommentResponses',
            fields=[
                ('cmrUid', models.IntegerField(primary_key=True, serialize=False)),
                ('cmrCmtUidOP', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='original', to='mainApp.Comment')),
                ('cmrCmtUidResponder', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='responding', to='mainApp.Comment')),
            ],
        ),
        migrations.CreateModel(
            name='Discussion',
            fields=[
                ('dscUid', models.IntegerField(primary_key=True, serialize=False)),
                ('dscTopLevelYN', models.CharField(max_length=1)),
            ],
        ),
        migrations.CreateModel(
            name='Post',
            fields=[
                ('pstUid', models.IntegerField(primary_key=True, serialize=False)),
                ('pstEditedYN', models.CharField(max_length=1)),
            ],
        ),
        migrations.CreateModel(
            name='Redditor',
            fields=[
                ('rdtUid', models.IntegerField(primary_key=True, serialize=False)),
            ],
        ),
        migrations.CreateModel(
            name='Report',
            fields=[
                ('rptUid', models.IntegerField(primary_key=True, serialize=False)),
                ('rptCmtUid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mainApp.Comment')),
                ('rptRdtUidReportee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reported', to='mainApp.Redditor')),
                ('rptRdtUidReporter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reporting', to='mainApp.Redditor')),
            ],
        ),
        migrations.CreateModel(
            name='SubModerators',
            fields=[
                ('sumUid', models.IntegerField(primary_key=True, serialize=False)),
                ('sumRdtUid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mainApp.Redditor')),
            ],
        ),
        migrations.CreateModel(
            name='Subreddit',
            fields=[
                ('subUid', models.IntegerField(primary_key=True, serialize=False)),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('usrUid', models.IntegerField(primary_key=True, serialize=False)),
                ('usrRdtUid', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='mainApp.Redditor', verbose_name='reddit account for system user')),
            ],
        ),
        migrations.AddField(
            model_name='submoderators',
            name='sumSubUid',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mainApp.Subreddit'),
        ),
        migrations.AddField(
            model_name='post',
            name='pstRdtUidAuthor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mainApp.Redditor'),
        ),
        migrations.AddField(
            model_name='post',
            name='pstSubUid',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mainApp.Subreddit'),
        ),
        migrations.AddField(
            model_name='discussion',
            name='dscUsrUid',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mainApp.User'),
        ),
        migrations.AddField(
            model_name='comment',
            name='cmtPstUid',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mainApp.Post'),
        ),
        migrations.AddField(
            model_name='comment',
            name='cmtRdtUidAuthor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mainApp.Redditor'),
        ),
        migrations.AddField(
            model_name='comment',
            name='cmtSubUid',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mainApp.Subreddit'),
        ),
    ]
