# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-02-07 02:07
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mainApp', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='SubModerator',
            new_name='Moderator',
        ),
        migrations.AlterModelTable(
            name='comment',
            table='comment',
        ),
        migrations.AlterModelTable(
            name='commentresponse',
            table='commentResponse',
        ),
        migrations.AlterModelTable(
            name='itemcomment',
            table='itemComment',
        ),
        migrations.AlterModelTable(
            name='itemcommentresponse',
            table='itemCommentResponse',
        ),
        migrations.AlterModelTable(
            name='itemstatus',
            table='itemStatus',
        ),
        migrations.AlterModelTable(
            name='itemtype',
            table='itemType',
        ),
        migrations.AlterModelTable(
            name='moderator',
            table='moderator',
        ),
        migrations.AlterModelTable(
            name='post',
            table='post',
        ),
        migrations.AlterModelTable(
            name='redditor',
            table='redditor',
        ),
        migrations.AlterModelTable(
            name='report',
            table='report',
        ),
        migrations.AlterModelTable(
            name='subreddit',
            table='subreddit',
        ),
        migrations.AlterModelTable(
            name='user',
            table='user',
        ),
        migrations.AlterModelTable(
            name='workitem',
            table='workItem',
        ),
    ]
