# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-02-05 06:24
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainApp', '0002_auto_20160205_0601'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='redditor',
            name='rdtUid',
        ),
        migrations.AddField(
            model_name='redditor',
            name='id',
            field=models.AutoField(auto_created=True, default=1001, primary_key=True, serialize=False, verbose_name='ID'),
            preserve_default=False,
        ),
    ]
