# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-02-07 01:06
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mainApp', '0003_auto_20160205_0624'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comment',
            name='cmtPstUid',
        ),
        migrations.RemoveField(
            model_name='comment',
            name='cmtRdtUidAuthor',
        ),
        migrations.RemoveField(
            model_name='comment',
            name='cmtSubUid',
        ),
        migrations.RemoveField(
            model_name='commentresponse',
            name='cmrCmtUidOP',
        ),
        migrations.RemoveField(
            model_name='commentresponse',
            name='cmrCmtUidResponder',
        ),
        migrations.RemoveField(
            model_name='discussion',
            name='dscUsrUid',
        ),
        migrations.RemoveField(
            model_name='post',
            name='pstRdtUidAuthor',
        ),
        migrations.RemoveField(
            model_name='post',
            name='pstSubUid',
        ),
        migrations.RemoveField(
            model_name='report',
            name='rptCmtUid',
        ),
        migrations.RemoveField(
            model_name='report',
            name='rptRdtUidReportee',
        ),
        migrations.RemoveField(
            model_name='report',
            name='rptRdtUidReporter',
        ),
        migrations.RemoveField(
            model_name='submoderator',
            name='sumRdtUid',
        ),
        migrations.RemoveField(
            model_name='submoderator',
            name='sumSubUid',
        ),
        migrations.RemoveField(
            model_name='user',
            name='usrRdtUid',
        ),
        migrations.DeleteModel(
            name='Comment',
        ),
        migrations.DeleteModel(
            name='CommentResponse',
        ),
        migrations.DeleteModel(
            name='Discussion',
        ),
        migrations.DeleteModel(
            name='Post',
        ),
        migrations.DeleteModel(
            name='Redditor',
        ),
        migrations.DeleteModel(
            name='Report',
        ),
        migrations.DeleteModel(
            name='SubModerator',
        ),
        migrations.DeleteModel(
            name='Subreddit',
        ),
        migrations.DeleteModel(
            name='User',
        ),
    ]
