# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-02-07 01:24
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainApp', '0005_auto_20160207_0107'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comment',
            name='id',
        ),
        migrations.RemoveField(
            model_name='commentresponse',
            name='id',
        ),
        migrations.RemoveField(
            model_name='itemcomment',
            name='id',
        ),
        migrations.RemoveField(
            model_name='itemcommentresponse',
            name='id',
        ),
        migrations.RemoveField(
            model_name='itemstatus',
            name='id',
        ),
        migrations.RemoveField(
            model_name='itemtype',
            name='id',
        ),
        migrations.RemoveField(
            model_name='post',
            name='id',
        ),
        migrations.RemoveField(
            model_name='redditor',
            name='id',
        ),
        migrations.RemoveField(
            model_name='report',
            name='id',
        ),
        migrations.RemoveField(
            model_name='submoderator',
            name='id',
        ),
        migrations.RemoveField(
            model_name='subreddit',
            name='id',
        ),
        migrations.RemoveField(
            model_name='user',
            name='id',
        ),
        migrations.RemoveField(
            model_name='workitem',
            name='id',
        ),
        migrations.AddField(
            model_name='comment',
            name='commentID',
            field=models.IntegerField(default='', primary_key=True, serialize=False),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='commentresponse',
            name='commentResponseID',
            field=models.IntegerField(default='', primary_key=True, serialize=False),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='itemcomment',
            name='itemCommentID',
            field=models.IntegerField(default='', primary_key=True, serialize=False),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='itemcommentresponse',
            name='itemCommentResponse',
            field=models.IntegerField(default='', primary_key=True, serialize=False),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='itemstatus',
            name='itemStatusID',
            field=models.IntegerField(default='', primary_key=True, serialize=False),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='itemtype',
            name='itemTypeID',
            field=models.IntegerField(default='', primary_key=True, serialize=False),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='post',
            name='postID',
            field=models.IntegerField(default='', primary_key=True, serialize=False),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='redditor',
            name='redditorID',
            field=models.IntegerField(default='', primary_key=True, serialize=False),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='report',
            name='reportID',
            field=models.IntegerField(default='', primary_key=True, serialize=False),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='submoderator',
            name='moderatorID',
            field=models.IntegerField(default='', primary_key=True, serialize=False),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='subreddit',
            name='subID',
            field=models.IntegerField(default='', primary_key=True, serialize=False),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='user',
            name='userID',
            field=models.IntegerField(default='', primary_key=True, serialize=False),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='workitem',
            name='workItemID',
            field=models.IntegerField(default='', primary_key=True, serialize=False),
            preserve_default=False,
        ),
    ]
